export const ROOT_NODE_TOP = 0
export const MAIN_NODE_COLOR = 'yellow'
export const SECOND_LEVEL_NODE_COLOR = '#e7c699'
export const MAIN_NODE_HEIGHT = 40
export const MAIN_NODE_WIDTH_MIN = 210
export const MAIN_NODE_WIDTH = 240
export const MAIN_NODE_WIDTH_MAX = 270
export const NODE_MARGIN = 5
export const NODE_LEFT = 20 // 节点最小left距离
export const BASIC_W = 120 // 左右节点间距
